name: Python package

on:
  # 매 정각(KST 기준, GitHub Actions는 UTC 기준이므로 매 UTC 정각에 실행됩니다.
  # UTC 정각은 KST로 환산하면 09시부터 다음날 08시까지의 정각이 됩니다.)
  schedule:
    - cron: '0 * * * *'

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt    
    - name: Test with pytest
      run: |        
        python nv_visitor.py  ${{ secrets.TELEGRAM_TOKEN }}
